// <auto-generated />
using System;
using Crud_DasignoSAS.Clases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crud_DasignoSAS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crud_DasignoSAS.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("Datetime")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("Datetime")
                        .HasColumnName("FechaModificacion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("Datetime")
                        .HasColumnName("FechaNacimiento");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PrimerApellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PrimerNombre");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SegundoApellido");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SegundoNombre");

                    b.Property<int>("Sueldo")
                        .HasColumnType("int")
                        .HasColumnName("Sueldo");

                    b.HasKey("Id");

                    b.ToTable("Datos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
